//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2022. All Rights Reserved.
//      RuleApp: Configuration_D_ploiement_Assurance
//      Date: 2 déc. 2022 à 10:25:39
//      Generated by: Decision Server 8.10.2.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package clientexecutionlocaleassurance;

import clientexecutionlocaleassurance.invocation.ODAssuranceExecution;
import pn.EnsembleCotisation;

/**
 * Point d'entrée de l'application
 */
public class Main {

	/**
	 * L'exécution démarre ici...
	 */
	public static void main(String[] args) throws Exception {

		ODAssuranceExecution OD_Assurance = new ODAssuranceExecution();
		pn.Contrat contrat = new pn.Contrat(0.8, 1.1, "B1", 200.0, null, 0.03, 1.00200, 0.970, 2020);
		pn.Garantie g1 = new pn.Garantie("Déteriorations Immobilières","029");
		contrat.getGaranties().add(g1);
		OD_Assurance.setContrat(contrat);
		// TODO insérez votre code pour initialiser 'ensembeCotisation'
		EnsembleCotisation cotisations = new EnsembleCotisation();
		OD_Assurance.setEnsembeCotisation(cotisations);

		// Cette méthode appelle l'ensemble de règles 'OD_Assurance'
		OD_Assurance.run();

		
		// TODO insérez votre code pour traiter la réponse
		System.out.println(cotisations.resumeCotisation());

	}

}
