//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2022. All Rights Reserved.
//      RuleApp: Configuration_deploiemnet_agence_voyage
//      Date: 1 déc. 2022 à 10:41:44
//      Generated by: Decision Server 8.10.2.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package agencevoyagejunit.invocation;

import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;

/**
 * Classe d'encapsuleur permettant l'appel de l'ensemble de règles
 * 'OD_AgenceVoyages'
 */
public class ODAgenceVoyagesExecution extends RulesetExecution {

	private pn.src.Demande demande;

	/**
	 * Renvoie le demande
	 */
	public pn.src.Demande getDemande() {
		return demande;
	}

	/**
	 * Définit le demande
	 */
	public void setDemande(pn.src.Demande demande) {
		this.demande = demande;
	}

	private pn.src.Reservation resa;

	/**
	 * Renvoie le resa
	 */
	public pn.src.Reservation getResa() {
		return resa;
	}

	/**
	 * Définit le resa
	 */
	public void setResa(pn.src.Reservation resa) {
		this.resa = resa;
	}

	/**
	 * Chemin d'accès à l'ensemble de règles 'OD_AgenceVoyages' le plus récent dans
	 * le référentiel
	 */
	protected String getRulesetPath() {
		return "/Configuration_deploiemnet_agence_voyage/1.0/OD_AgenceVoyages";
	}

	/**
	 * Initialiser la session de requête avec des valeurs pour les paramètres
	 * d'entrée
	 */
	protected void initRequest(IlrSessionRequest request) {
		request.setInputParameter("demande", this.demande);
		request.setInputParameter("resa", this.resa);
	}

	/**
	 * Récupérer les valeurs dans la réponse des paramètres de sortie
	 */
	protected void handleResponse(IlrSessionResponse response) {
		this.resa = (pn.src.Reservation) response.getOutputParameters().get("resa");
	}

}
