//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2022. All Rights Reserved.
//      RuleApp: Configuration_deploiemnet_agence_voyage
//      Date: 30 nov. 2022 à 14:21:50
//      Generated by: Decision Server 8.10.2.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package clientexecutionlocal;

import clientexecutionlocal.invocation.ODAgenceVoyagesExecution;
import pn.src.Demande;
import pn.src.Passager;

/**
 * Point d'entrée de l'application
 */
public class Main {

	/**
	 * L'exécution démarre ici...
	 */
	public static void main(String[] args) throws Exception {

		ODAgenceVoyagesExecution OD_AgenceVoyages = new ODAgenceVoyagesExecution();
		int i =0;
		long j, k;
		System.out.println("démarrage");
		j = System.currentTimeMillis();
		while ( i<1000) {
		// TODO insérez votre code pour initialiser 'demande'
		pn.src.Passager p1 = new pn.src.Passager("titi","toto",25+i,"carte 12-25");
		pn.src.Demande dem = new pn.src.Demande("Paris","Nantes",1,100+i,2,null);
		dem.getPassagers().add(p1);
		
		OD_AgenceVoyages.setDemande(dem);
		// TODO insérez votre code pour initialiser 'resa'
		pn.src.Reservation resa = new pn.src.Reservation();
		OD_AgenceVoyages.setResa(resa);

		// Cette méthode appelle l'ensemble de règles 'OD_AgenceVoyages'
	
		OD_AgenceVoyages.run();
		i++;
		
		// TODO insérez votre code pour traiter la réponse
		//System.out.println(OD_AgenceVoyages.getResa().resumeReservation());
		}
		k = System.currentTimeMillis();
		System.out.println( "durée d'exécution pour " + i + " itérations : " + (k - j)/1000);
	}	

}
