//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2022. All Rights Reserved.
//      RuleApp: Configuration_deploiemnet_agence_voyage
//      Date: 1 déc. 2022 à 10:41:44
//      Generated by: Decision Server 8.10.2.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package agencevoyagejunit;

import agencevoyagejunit.invocation.ODAgenceVoyagesExecution;
import junit.framework.TestCase;

/**
 * Scénario de test de l'ensemble de règles 'OD_AgenceVoyages'
 */
public class ODAgenceVoyagesTestCase extends TestCase {

	/**
	 * TODO Fournissez des données et évaluez les résultats de l'appel.
	 */
	public void testOne() throws Exception {

		ODAgenceVoyagesExecution OD_AgenceVoyages = new ODAgenceVoyagesExecution();

		// TODO insérez votre code pour initialiser 'demande'
		pn.src.Passager p1 = new pn.src.Passager("titi","toto",25,"carte 12-25");
		pn.src.Demande dem = new pn.src.Demande("Paris","Nantes",1,100,2,null);
		dem.getPassagers().add(p1);
		
		OD_AgenceVoyages.setDemande(dem);
		// TODO insérez votre code pour initialiser 'resa'
		pn.src.Reservation resa = new pn.src.Reservation();
		OD_AgenceVoyages.setResa(resa);

		// Cette méthode appelle l'ensemble de règles 'OD_AgenceVoyages'
	
		OD_AgenceVoyages.run();
		System.out.println(resa.resumeReservation());
		assertTrue("Etat de la réservation : ", resa.getEtat().equals("Validé"));
		assertTrue("Prix de la réservation : ", resa.getPrixTotal()<50);



	}

}
