//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2022. All Rights Reserved.
//      RuleApp: Configuration_D_ploiement_Assurance
//      Date: 2 déc. 2022 à 10:34:21
//      Generated by: Decision Server 8.10.2.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package assurancejunit.invocation;

import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;

/**
 * Classe d'encapsuleur permettant l'appel de l'ensemble de règles
 * 'OD_Assurance'
 */
public class ODAssuranceExecution extends RulesetExecution {

	private pn.Contrat contrat;

	/**
	 * Renvoie le contrat
	 */
	public pn.Contrat getContrat() {
		return contrat;
	}

	/**
	 * Définit le contrat
	 */
	public void setContrat(pn.Contrat contrat) {
		this.contrat = contrat;
	}

	private pn.EnsembleCotisation ensembeCotisation;

	/**
	 * Renvoie le ensembeCotisation
	 */
	public pn.EnsembleCotisation getEnsembeCotisation() {
		return ensembeCotisation;
	}

	/**
	 * Définit le ensembeCotisation
	 */
	public void setEnsembeCotisation(pn.EnsembleCotisation ensembeCotisation) {
		this.ensembeCotisation = ensembeCotisation;
	}

	/**
	 * Chemin d'accès à l'ensemble de règles 'OD_Assurance' le plus récent dans le
	 * référentiel
	 */
	protected String getRulesetPath() {
		return "/Configuration_D_ploiement_Assurance/1.0/OD_Assurance";
	}

	/**
	 * Initialiser la session de requête avec des valeurs pour les paramètres
	 * d'entrée
	 */
	protected void initRequest(IlrSessionRequest request) {
		request.setInputParameter("contrat", this.contrat);
		request.setInputParameter("ensembeCotisation", this.ensembeCotisation);
	}

	/**
	 * Récupérer les valeurs dans la réponse des paramètres de sortie
	 */
	protected void handleResponse(IlrSessionResponse response) {
		this.ensembeCotisation = (pn.EnsembleCotisation) response.getOutputParameters().get("ensembeCotisation");
	}

}
